### ISSUE TITLE
Adhere to the PEP8 Style Guide

### ISSUE THREAD

**Issue by ilyakam** [ilyakam/RemoveDuplicateLines#29]
Specifically:

* Use four spaces per indentation level ([source](https://www.python.org/dev/peps/pep-0008/#indentation))
* Consider applying other indentation rules as seen in 49e4a0d5afb576989cd1f18f83d630ae3421195d
* Update [`.editorconfig`](https://github.com/ilyakam/RemoveDuplicateLines/blob/develop/.editorconfig)

**Comment by GiovanH** [comment]
Seems a bit obvious, but I'm suggesting https://github.com/ilyakam/RemoveDuplicateLines/commit/49e4a0d5afb576989cd1f18f83d630ae3421195d as a resolution.

**Comment by GiovanH** [comment]
@ilyakam Is there any reason not to cherry-pick that commit to resolve this issue?

**Comment by ilyakam** [comment]
All done now -- [see release 2.1.1](https://github.com/ilyakam/RemoveDuplicateLines/releases/tag/2.1.1). Apologies for taking this long. LMK if I missed anything.
